/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoprogramado;

import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static proyectoprogramado.VariablesGlobales.vehiculosNuevos;
import static proyectoprogramado.VariablesGlobales.vehiculosUsados;
/**
 *
 * @author cgari
 */
public class ListadoCotizaciones extends javax.swing.JDialog {

    //Declaración de las variables de instancia
    private DefaultTableModel modeloTabla;
    private DefaultTableModel modeloTabla2;

    /**
     * Creates new form ListadoCotizaciones
     */
    public ListadoCotizaciones(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents(); //Inicializa los componentes en pantalla
        this.setLocationRelativeTo(null); //Posiciona el JDialog en el centro de la pantalla  

        //Agrega los radioButtons a un ButtonGroup
        this.btgCotizaciones.add(rdbVNuevo);
        this.btgCotizaciones.add(rdbVUsado);

        //Establece el estado inicial de las tablas
        this.tbCotizacionesNuevos.setEnabled(false);
        this.tbCotizacionesUsados.setEnabled(false);

        //Ejecuta el método
        this.cargarDatos();
    }

    public void cargarDatos() {

        //Crea un modelo para la tabla
        this.modeloTabla = new DefaultTableModel() {

            //Método para impedir que la la información de la tabla sea editable de forma directa por el usuario
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; //Regresa el valor de la variable
            }
        };

        //Se establecen los nombres de los encabezados de las columnas de la tabla
        modeloTabla.addColumn("N° Cotización");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Cédula");

        //Se define un objeto para manejar la informacion a ingresar en cada fila
        Object[] fila;
        this.tbCotizacionesNuevos.setModel(modeloTabla); //Se establece el modelo de la tabla 
        
//Ciclo para recorrer un objeto
        for (DatosPersonales d : vehiculosNuevos) {

            //Se define un array de 3 campos y se asigna a la variable "fila"
            fila = new Object[3];

            //Se asignan los valores de las variables de instancia del objeto a cada campo del array "fila"
            fila[0] = d.getNumeroCotizacion();
            fila[1] = d.getNombre();
            fila[2] = d.getIdentificacion();

            modeloTabla.addRow(fila); //Se adicionan los valores del array "fila" a una fila del modelo de la tabla           
        }

        //Crea un modelo para la tabla
        this.modeloTabla2 = new DefaultTableModel() {

            //Método para impedir que la la información de la tabla sea editable de forma directa por el usuario 
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; //Regresa el valor de la variable
            }
        };

        //Se establecen los nombres de los encabezados de las columnas de la tabla
        modeloTabla2.addColumn("N° Cotización");
        modeloTabla2.addColumn("Nombre");
        modeloTabla2.addColumn("Cédula");

        this.tbCotizacionesUsados.setModel(modeloTabla2); //Se establece el modelo de la tabla 
        //Ciclo para recorrer un objeto 
        for (DatosPersonales d : vehiculosUsados) {

            //Se define un array de 3 campos y se asigna a la variable "fila"
            fila = new Object[3];

            //Se asignan los valores de las variables de instancia del objeto p a cada campo del array "fila"
            fila[0] = d.getNumeroCotizacion();
            fila[1] = d.getNombre();
            fila[2] = d.getIdentificacion();

            modeloTabla2.addRow(fila); //Se adicionan los valores del array "fila" a una fila del modelo de la tabla           
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgCotizaciones = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCotizacionesUsados = new javax.swing.JTable();
        btnBuscarCot = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rdbVUsado = new javax.swing.JRadioButton();
        rdbVNuevo = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCotizacionesNuevos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tbCotizacionesUsados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbCotizacionesUsados);

        btnBuscarCot.setText("Buscar Cotización");
        btnBuscarCot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCotActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Tipo de cotización a buscar:");

        rdbVUsado.setText("Vehículo Usado");
        rdbVUsado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbVUsadoActionPerformed(evt);
            }
        });

        rdbVNuevo.setText("Vehículo Nuevo");
        rdbVNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbVNuevoActionPerformed(evt);
            }
        });

        tbCotizacionesNuevos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbCotizacionesNuevos);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Vehículos Usados:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Vehículos Nuevos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbVNuevo)
                    .addComponent(rdbVUsado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(btnBuscarCot)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdbVUsado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdbVNuevo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnBuscarCot)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbVUsadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbVUsadoActionPerformed
        //Establece los valores según la selección del radioButton
        this.tbCotizacionesNuevos.setEnabled(false);
        this.tbCotizacionesUsados.setEnabled(true);
    }//GEN-LAST:event_rdbVUsadoActionPerformed

    private void rdbVNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbVNuevoActionPerformed
        //Establece los valores según la selección del radioButton
        this.tbCotizacionesNuevos.setEnabled(true);
        this.tbCotizacionesUsados.setEnabled(false);
    }//GEN-LAST:event_rdbVNuevoActionPerformed

    private void btnBuscarCotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCotActionPerformed
        if(this.rdbVNuevo.isSelected()) {
            //Obtiene un valor númerico en caso de que la fila se encuentre seleccionada y lo asigna a una variable local "fila"
            int fila = this.tbCotizacionesNuevos.getSelectedRow();

            //Condicional para determinar si la fila se encuentra seleccionada para continuar con el formulario de edición de datos
            if (fila != -1) {

                //Obtiene el valor del número de cotización en la fila seleccionada de la tabla y lo almacena en una variable local llamada "id"
                int id = (int) this.tbCotizacionesNuevos.getValueAt(fila, 0);

                String tipo = "Nuevo";

                //Crea el objeto "ventana" de la clase "Mensaje" y lo inicializa mediante el método constructor "Mensaje"
                Mensaje ventana = new Mensaje(new javax.swing.JDialog(), true, tipo, id);

                //Hace visible el objeto ventana
                ventana.setVisible(true);

            } else {
                //Muestra mensaje en pantalla 
                JOptionPane.showMessageDialog(this,
                        "Debe seleccionar el número de cotización para continuar",
                        "Alto",
                        JOptionPane.WARNING_MESSAGE);
            }

        } else if (this.rdbVUsado.isSelected()) {
            //Obtiene un valor númerico en caso de que la fila se encuentre seleccionada y lo asigna a una variable local "fila"
            int fila = this.tbCotizacionesUsados.getSelectedRow();

            //Condicional para determinar si la fila se encuentra seleccionada para continuar con el formulario de edición de datos
            if (fila != -1) {

                //Obtiene el valor del número de cotización en la fila seleccionada de la tabla y lo almacena en una variable local llamada "id"
                int id = (int) this.tbCotizacionesUsados.getValueAt(fila, 0);

                String tipo = "Usado";

                //Crea el objeto "ventana" de la clase "Mensaje" y lo inicializa mediante el método constructor "Mensaje"
                Mensaje ventana = new Mensaje(new javax.swing.JDialog(), true, tipo, id);

                //Hace visible el objeto ventana
                ventana.setVisible(true);

            } else {
                //Muestra mensaje en pantalla 
                JOptionPane.showMessageDialog(this,
                        "Debe seleccionar el número de cotización para continuar",
                        "Alto",
                        JOptionPane.WARNING_MESSAGE);
            }

        } else {
            //Muestra mensaje en pantalla 
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar un tipo de cotización y el número de cotización para continuar",
                    "Alto",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarCotActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgCotizaciones;
    private javax.swing.JButton btnBuscarCot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdbVNuevo;
    private javax.swing.JRadioButton rdbVUsado;
    private javax.swing.JTable tbCotizacionesNuevos;
    private javax.swing.JTable tbCotizacionesUsados;
    // End of variables declaration//GEN-END:variables
}
