/*
Universidad: UNED
Curso:        Programación Intermedia 
Código:       00824
Tema:         Proyecto Programado (II Parcial)
Estudiante:   Carlos Garita Campos
Periodo:      I Cuatrimestre 2020
 */

package proyectoprogramado;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import static proyectoprogramado.VariablesGlobales.vehiculosNuevos;
import static proyectoprogramado.VariablesGlobales.vehiculosUsados;

public class PantallaPrincipal extends javax.swing.JFrame {

    //Constructor
    public PantallaPrincipal() {
        initComponents(); //Inicializa los componentes
        this.setLocationRelativeTo(null); //Posiciona el JFrame en el centro de la pantalla  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCrearCot = new javax.swing.JButton();
        btnMostrarCot = new javax.swing.JButton();
        btnSalirCot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnCrearCot.setText("Crear cotización");
        btnCrearCot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCotActionPerformed(evt);
            }
        });

        btnMostrarCot.setText("Mostrar cotizaciones");
        btnMostrarCot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarCotActionPerformed(evt);
            }
        });

        btnSalirCot.setText("Salir");
        btnSalirCot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirCotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(btnCrearCot)
                .addGap(51, 51, 51)
                .addComponent(btnMostrarCot)
                .addGap(43, 43, 43)
                .addComponent(btnSalirCot)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearCot)
                    .addComponent(btnMostrarCot)
                    .addComponent(btnSalirCot))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirCotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirCotActionPerformed
        FileOutputStream fichero = null;

        try {
            fichero = new FileOutputStream("cotizacionesSeguroNuevos.txt");
            ObjectOutputStream archivo;
            archivo = new ObjectOutputStream(fichero);
            archivo.writeObject(vehiculosNuevos);
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        } finally {
            try {
                fichero.close();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }

        try {
            fichero = new FileOutputStream("cotizacionesSeguroUsados.txt");
            ObjectOutputStream archivo;
            archivo = new ObjectOutputStream(fichero);
            archivo.writeObject(vehiculosUsados);
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        } finally {
            try {
                fichero.close();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
        System.exit(0); //Finaliza el programa
    }//GEN-LAST:event_btnSalirCotActionPerformed

    private void btnCrearCotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCotActionPerformed
        //Crea el objeto "ventana" de la clase "CalculosSeguros" y lo inicializa mediante el método constructor "CalculosSeguros"
        CalculosSeguros ventana = new CalculosSeguros(new javax.swing.JDialog(), true);

        //Hace visible el objeto ventana
        ventana.setVisible(true);
    }//GEN-LAST:event_btnCrearCotActionPerformed

    private void btnMostrarCotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarCotActionPerformed
        //Crea el objeto "ventana" de la clase "ListadoCotizaciones" y lo inicializa mediante el método constructor "ListadoCotizaciones"
        ListadoCotizaciones ventana = new  ListadoCotizaciones(new javax.swing.JDialog(), true);
        
        //Hace visible el objeto ventana
        ventana.setVisible(true);
    }//GEN-LAST:event_btnMostrarCotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCot;
    private javax.swing.JButton btnMostrarCot;
    private javax.swing.JButton btnSalirCot;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
